[pytest]
pythonpath = .
testpaths =
    test
    nyc_cab/test
    nyc_cab/contracts/test
    nyc_cab/ingestion/test
    nyc_cab/orchestration/test
python_files = *.py
python_functions = test_*
python_classes = Test*
addopts =
    --strict-config
    --strict-markers
 